language: c
before_install:
  - sudo add-apt-repository -y ppa:fish-shell/nightly-master
  - sudo apt-get update
  - sudo apt-get -y install fish
  - git clone git://github.com/terlar/fish-tank.git
  - cd fish-tank
  - sudo make install
  - cd -

script: make test
